#!/usr/bin/env python3
"""Build icons.svg — the site's icon sprite — from Lucide's own SVG sources.

Site tooling only. fertig itself ships no icons and has no dependencies; this
sprite is committed to the repo so the site has no build step and makes no
third-party request at runtime.

    npm install --no-save lucide-static && python3 tools/build-icons.py

Lucide is ISC licensed. It carries no brand marks (no GitHub logo), so links
to a repository use git-branch rather than a vendored brand asset.
"""
import os, re, sys

ICONS = [
    'book-open', 'blocks', 'layout-dashboard', 'git-branch', 'package',
    'arrow-right', 'sun', 'moon', 'copy', 'check', 'zap', 'accessibility',
    'languages', 'layers', 'palette', 'file-code', 'terminal', 'scale',
]
SRC = 'node_modules/lucide-static/icons/%s.svg'
OUT = 'icons.svg'

def main():
    missing = [n for n in ICONS if not os.path.exists(SRC % n)]
    if missing:
        sys.exit('missing icons: ' + ', '.join(missing))

    version = 'unknown'
    try:
        import json
        version = json.load(open('node_modules/lucide-static/package.json'))['version']
    except Exception:
        pass

    out = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<!-- icons.svg — sprite built from Lucide {version} (ISC). https://lucide.dev',
        '     Site only: fertig itself ships no icons and has no dependencies.',
        '     Generated by tools/build-icons.py — edit that, not this file.',
        '     Stroke colour comes from currentColor at the use site. -->',
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">',
    ]
    for name in ICONS:
        # anchored to the end of the opening tag: Lucide formats its attributes
        # across lines, so a bare '>' would match inside the <svg> tag itself
        body = re.search(r'<svg\b[^>]*>(.*)</svg>', open(SRC % name).read(), re.S).group(1).strip()
        out.append(f'  <symbol id="{name}" viewBox="0 0 24 24" fill="none" '
                   'stroke="currentColor" stroke-width="2" stroke-linecap="round" '
                   'stroke-linejoin="round">')
        out += ['    ' + line.strip() for line in body.splitlines()]
        out.append('  </symbol>')
    out.append('</svg>')

    open(OUT, 'w').write('\n'.join(out) + '\n')
    print(f'{OUT}: {len(ICONS)} symbols, {os.path.getsize(OUT)} bytes')

if __name__ == '__main__':
    main()
